version: "3.9"

services:
  joomla:
    container_name: joomla
    restart: always
    init: true
    image: joomla:php7.3-apache
    ports:
      - "8080:80"
    volumes:
      - ./joomla:/var/www/html
    depends_on:
      - mysql
    links:
      - mysql:mysql
    environment:
      - JOOMLA_DB_HOST=${JOOMLA_DB_HOST}
      - JOOMLA_DB_USER=${JOOMLA_DB_USER}
      - JOOMLA_DB_PASSWORD=${JOOMLA_DB_PASSWORD}
      - JOOMLA_DB_NAME=${JOOMLA_DB_NAME}
    networks:
      - joomla-mysql

  mysql:
    container_name: mysql
    restart: always
    init: true
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - joomla-mysql

networks:
  joomla-mysql:
    driver: bridge
