version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/gzip.conf:/etc/nginx/conf.d/gzip.conf
      - ./log/nginx:/var/log/nginx
    depends_on:
      - ghost
    links:
      - ghost
    networks:
      - nginx-ghost

  ghost:
    container_name: ghost
    image: ghost:alpine
    ports:
      - "2368:2368"
    restart: always
    volumes:
      - ./ghost:/var/lib/ghost/content
    networks:
      - nginx-ghost

networks:
  nginx-ghost:
    driver: bridge
