version: "3"

services:
    nginx:
        container_name: nginx
        restart: always
        image: nginx:alpine
        ports:
            - "5200:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/gzip.conf:/etc/nginx/conf.d/gzip.conf
            - ./log/nginx:/var/log/nginx
        depends_on:
            - web
        links:
            - web
        networks:
            - nginx-ghost
    web:
        container_name: web
        restart: always
        image: ghost:alpine
        ports:
            - "2368:2368"
        volumes:
            - "./web:/var/lib/ghost/content"
        networks:
            - nginx-ghost

networks:
    nginx-ghost:
        driver: bridge
