version: "3.9"

services:
  php:
    container_name: php
    restart: always
    init: true
    image: php:8.0.5-apache
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks:
      - php-mysql-phpmyadmin

  mysql:
    container_name: mysql
    restart: always
    init: true
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - php-mysql-phpmyadmin

  phpmyadmin:
    container_name: phpmyadmin
    restart: always
    init: true
    image: phpmyadmin/phpmyadmin
    ports:
      - "9191:80"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_HOST=${PMA_HOST:-mysql}
    depends_on:
      - mysql
    links:
      - mysql:mysql
    networks:
      - php-mysql-phpmyadmin

networks:
  php-mysql-phpmyadmin:
    driver: bridge
