version: "3.9"

services:
  nginx:
    container_name: nginx
    restart: always
    init: true
    image: nginx:1.17.6-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/gzip.conf:/etc/nginx/conf.d/gzip.conf
      - ./log/nginx:/var/log/nginx
    depends_on:
      - node
    networks:
      - nginx-node-mongo

  node:
    container_name: node
    restart: always
    init: true
    build: ./web
    ports:
      - "8080:80"
    volumes:
      - ./web/src:/usr/src/web/src
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - nginx-node-mongo

  mongo:
    container_name: mongo
    restart: always
    init: true
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - nginx-node-mongo

networks:
  nginx-node-mongo:
    driver: bridge
