version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/gzip.conf:/etc/nginx/conf.d/gzip.conf
      - ./log/nginx:/var/log/nginx
    depends_on:
      - node
    networks:
      - nginx-node-mongo

  node:
    container_name: node
    build: ./web
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./web/src:/usr/src/web/src
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - nginx-node-mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    networks:
      - nginx-node-mongo

networks:
  nginx-node-mongo:
    driver: bridge
