version: "3"

services:
    web:
        container_name: web
        restart: always
        image: wordpress
        ports:
            - "5200:80"
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: pass
        volumes:
            - ./web:/var/www/html
        depends_on:
            - db
        links:
            - db
        networks:
            - wordpress

    db:
        container_name: db
        restart: always
        image: mariadb
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: root
            MYSQL_PASSWORD: pass
            MYSQL_ROOT_PASSWORD: pass
        volumes:
            - ./data:/var/lib/mysql
        networks:
            - wordpress

networks:
    wordpress:
        driver: bridge
