version: "3.9"

services:
  jenkins:
    container_name: jenkins
    restart: always
    init: true
    image: jenkins:2.60.3-alpine
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./data/jenkins:/var/jenkins_home
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge
