version: "3"

services:
    jenkins:
	    container-name: jenkins
        restart: always
        image: jenkins/jenkins:alpine
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - ./data:/var/jenkins_home
        networks:
            - jenkins

networks:
    jenkins:
        driver: bridge
