version: "3"

services:
  joomla:
    container_name: joomla
    image: joomla:latest
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./joomla:/var/www/html
    depends_on:
      - mysql
    links:
      - mysql:mysql
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_NAME: joomla
      JOOMLA_DB_USER: root
      JOOMLA_DB_PASSWORD: pass
    networks:
      - joomla-mysql-phpmyadmin

  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    networks:
      - joomla-mysql-phpmyadmin

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "9191:80"
    restart: always
    depends_on:
      - mysql
    links:
      - mysql:mysql
    environment:
      PMA_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    networks:
      - joomla-mysql-phpmyadmin

networks:
  joomla-mysql-phpmyadmin:
    driver: bridge
